-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 10:02:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rio Grande lanches
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rio Grande lanches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Rio Grande lanches` DEFAULT CHARACTER SET utf8 ;
USE `Rio Grande lanches` ;

-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`administradores` (
  `Nome` VARCHAR(300) NULL,
  `telefone` VARCHAR(9) NULL,
  `email` VARCHAR(200) NULL,
  `senha` VARCHAR(45) NULL,
  `ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`entregadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`entregadores` (
  `Nome` VARCHAR(300) NULL,
  `telefone` VARCHAR(9) NULL,
  `foto de perfil` VARCHAR(45) NULL,
  `email` VARCHAR(200) NULL,
  `senha` VARCHAR(45) NULL,
  `ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`clientes` (
  `telefone` VARCHAR(9) NULL,
  `nome` VARCHAR(300) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(200) NULL,
  `matrícula` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`matrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`lanches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`lanches` (
  `preco` DECIMAL(2) NULL,
  `nome` VARCHAR(300) NULL,
  `descricao` VARCHAR(500) NULL,
  `categoria` VARCHAR(100) NULL,
  `id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`pedidos` (
  `forma e pagamentos` VARCHAR(150) NULL,
  `taxa de entrega` DECIMAL(2) NULL,
  `data/hora` DATETIME NULL,
  `status de pedido` VARCHAR(450) NULL,
  `quantidade` INT NULL,
  `pedidoscol` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`restaurantes` (
  `cnpj` VARCHAR(14) NULL,
  `telefone` VARCHAR(9) NULL,
  `nome` VARCHAR(300) NULL,
  `tempo de preparo estimado` TIME NULL,
  `sala` VARCHAR(45) NULL,
  `predio` VARCHAR(45) NULL,
  `id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`carinhodecompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`carinhodecompras` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`pagamentos` (
  `id` VARCHAR(32) NOT NULL,
  `formadepagamento` VARCHAR(45) NULL,
  `statusdepagamento` VARCHAR(4150) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`enderecocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`enderecocliente` (
  `sala` VARCHAR(200) NULL,
  `oredio` VARCHAR(200) NULL,
  `n.casa` VARCHAR(200) NULL,
  `idaluno` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idaluno`),
  CONSTRAINT `fk_multicliente`
    FOREIGN KEY (`idaluno`)
    REFERENCES `Rio Grande lanches`.`clientes` (`matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rio Grande lanches`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rio Grande lanches`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
